import { Inter } from "next/font/google";
import "../../public/css/style.css"
import "../../public/css/bootstrap.min.css"
import Script from "next/script";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Script src="/js/bootstrap.bundle.min.js"></Script>
    </html>
  );
}
